FROM ubuntu

#Update APT using apt-get update
RUN apt-get update

#upgrade currently installed software through apt-get upgrade -y
RUN apt-get update -y

#echo hello world unto the terminal
CMD [echo, 'Hello World!']